# Generated by Django 2.2.13 on 2021-02-28 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_stream_id', models.CharField(max_length=30, verbose_name='订单编号')),
                ('body', models.CharField(default='', max_length=60, verbose_name='订单内容')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='下单时间')),
            ],
            options={
                'ordering': ['createtime'],
            },
        ),
    ]
