# Generated by Django 3.1.6 on 2021-02-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articleid', models.CharField(default='', max_length=30, verbose_name='文章id')),
                ('article', models.CharField(default='', max_length=30, verbose_name='文章内容')),
                ('createtime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['createtime'],
            },
        ),
    ]
