# Generated by Django 3.1.6 on 2021-02-14 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='auth.user'),
            preserve_default=False,
        ),
    ]
