# Generated by Django 2.2.13 on 2021-02-27 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bbs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='', max_length=30, verbose_name='昵称')),
                ('phone_number', models.CharField(blank=True, max_length=20, unique=True, verbose_name='手机')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('description', models.CharField(default='', max_length=30, verbose_name='个人简介')),
                ('score', models.BigIntegerField(default=0, verbose_name='积分')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
            },
        ),
    ]
